const KNOWLEDGE_BASE = {
  rules: [
    // === SKS & IPK RULES ===
    { rule_id:"R001", category:"SKS", priority:1, conditions:[{field:"ipk",op:">=",val:3.0}], result:{max_sks:24}, template:"Mahasiswa dengan IPK {ipk} (≥ 3.00) dapat mengambil maksimal **24 SKS** pada semester berikutnya.", source:"Peraturan Akademik UNILA 2025 Pasal 24 ayat (5)" },
    { rule_id:"R002", category:"SKS", priority:2, conditions:[{field:"ipk",op:">=",val:2.5},{field:"ipk",op:"<",val:3.0}], result:{max_sks:21}, template:"Mahasiswa dengan IPK {ipk} (2.50–2.99) dapat mengambil maksimal **21 SKS**.", source:"Peraturan Akademik UNILA 2025 Pasal 24 ayat (5)" },
    { rule_id:"R003", category:"SKS", priority:3, conditions:[{field:"ipk",op:">=",val:2.0},{field:"ipk",op:"<",val:2.5}], result:{max_sks:18}, template:"Mahasiswa dengan IPK {ipk} (2.00–2.49) dapat mengambil maksimal **18 SKS**.", source:"Peraturan Akademik UNILA 2025 Pasal 24 ayat (5)" },
    { rule_id:"R004", category:"SKS", priority:4, conditions:[{field:"ipk",op:">=",val:1.5},{field:"ipk",op:"<",val:2.0}], result:{max_sks:15}, template:"Mahasiswa dengan IPK {ipk} (1.50–1.99) hanya dapat mengambil maksimal **15 SKS**. Perhatian: IPK Anda perlu ditingkatkan.", source:"Peraturan Akademik UNILA 2025 Pasal 24 ayat (5)" },
    { rule_id:"R004B", category:"SKS", priority:5, conditions:[{field:"ipk",op:"<",val:1.5}], result:{max_sks:12}, template:"⚠️ Mahasiswa dengan IPK {ipk} (< 1.50) hanya dapat mengambil maksimal **12 SKS**. IPK sangat rendah, segera konsultasi dengan PA!", source:"Peraturan Akademik UNILA 2025 Pasal 24 ayat (5)" },
    { rule_id:"R005", category:"SKS", priority:1, conditions:[{field:"semester",op:"<=",val:2}], result:{max_sks:20}, template:"Mahasiswa semester 1-2 dapat mengambil maksimal **20 SKS** (paket ditentukan program studi).", source:"Peraturan Akademik UNILA 2025 Pasal 24 ayat (5)" },

    // === KEHADIRAN / PRESENSI ===
    { rule_id:"R006", category:"Kehadiran", priority:1, conditions:[{field:"presensi",op:">=",val:80}], result:{boleh_uts:true,boleh_uas:true}, template:"Kehadiran {presensi}% memenuhi syarat minimum 80%. Anda **diizinkan mengikuti UTS dan UAS**.", source:"Peraturan Akademik UNILA 2025 Pasal 34" },
    { rule_id:"R007", category:"Kehadiran", priority:2, conditions:[{field:"presensi",op:">=",val:50},{field:"presensi",op:"<",val:80}], result:{boleh_uts:true,boleh_uas:false}, template:"Kehadiran {presensi}% hanya memenuhi syarat UTS, namun **tidak memenuhi syarat untuk UAS**. Kehadiran minimum untuk UAS adalah 80%.", source:"Peraturan Akademik UNILA 2025 Pasal 34" },
    { rule_id:"R008", category:"Kehadiran", priority:3, conditions:[{field:"presensi",op:"<",val:50}], result:{boleh_uts:false,boleh_uas:false}, template:"Kehadiran {presensi}% **tidak memenuhi syarat UTS maupun UAS**. Anda berisiko mendapat nilai E pada mata kuliah tersebut.", source:"Peraturan Akademik UNILA 2025 Pasal 34" },
    { rule_id:"R009", category:"Kehadiran", priority:1, conditions:[{field:"presensi",op:">=",val:80}], result:{nilai_bonus:true}, template:"Kehadiran {presensi}% (≥80%) dapat memberikan pertimbangan nilai tambahan dari dosen sesuai kebijakan program studi.", source:"Peraturan Akademik UNILA 2025 Pasal 34" },

    // === UTS & UAS ===
    { rule_id:"R010", category:"UAS", priority:1, conditions:[{field:"presensi",op:">=",val:80},{field:"administrasi",op:"==",val:true}], result:{boleh_uas:true}, template:"Syarat UAS terpenuhi: kehadiran ≥80% dan administrasi lunas. **Anda berhak mengikuti UAS**.", source:"Peraturan Akademik UNILA 2025 Pasal 34" },
    { rule_id:"R011", category:"UAS", priority:2, conditions:[{field:"administrasi",op:"==",val:false}], result:{boleh_uas:false}, template:"**Administrasi belum lunas.** Anda tidak diizinkan mengikuti UAS hingga kewajiban administrasi dipenuhi. Segera hubungi BAAK.", source:"Peraturan Akademik UNILA 2025 Pasal 34" },
    { rule_id:"R012", category:"UTS", priority:1, conditions:[{field:"presensi",op:">=",val:50}], result:{boleh_uts:true}, template:"Kehadiran {presensi}% memenuhi syarat minimum UTS (≥50%). **Anda diizinkan mengikuti UTS**.", source:"Peraturan Akademik UNILA 2025 Pasal 34" },

    // === SEMESTER PENDEK ===
    { rule_id:"R013", category:"SemesterPendek", priority:1, conditions:[{field:"ipk",op:"<",val:2.0}], result:{prioritas_sp:true,max_sks_sp:9}, template:"Mahasiswa dengan IPK < 2.00 **diprioritaskan** mengikuti Semester Pendek (SP) dengan maksimal 9 SKS untuk perbaikan nilai.", source:"Peraturan Akademik UNILA 2025 Pasal 6" },
    { rule_id:"R014", category:"SemesterPendek", priority:2, conditions:[{field:"ipk",op:">=",val:2.0}], result:{boleh_sp:true,max_sks_sp:9}, template:"Mahasiswa dengan IPK ≥ 2.00 **dapat mengikuti** Semester Pendek maksimal 9 SKS untuk memperbaiki nilai atau mengulang.", source:"Peraturan Akademik UNILA 2025 Pasal 6" },
    { rule_id:"R015", category:"SemesterPendek", priority:1, conditions:[{field:"semester",op:">=",val:2}], result:{eligible_sp:true}, template:"Semester Pendek hanya dapat diikuti mulai **semester 2** ke atas. Mahasiswa semester 1 tidak diperkenankan.", source:"Peraturan Akademik UNILA 2025 Pasal 6" },
    { rule_id:"R016", category:"SemesterPendek", priority:1, conditions:[], result:{biaya_sp:true}, template:"Semester Pendek dikenakan **biaya tambahan** di luar UKT reguler. Informasi biaya dapat diperoleh di BAAK UNILA.", source:"Peraturan Akademik UNILA 2025 Pasal 6" },

    // === SKRIPSI / TUGAS AKHIR ===
    { rule_id:"R017", category:"Skripsi", priority:1, conditions:[{field:"sks_lulus",op:">=",val:80},{field:"ipk",op:">=",val:2.0}], result:{boleh_skripsi:true}, template:"Syarat pengajuan skripsi terpenuhi: SKS lulus ≥80 dan IPK ≥ 2.00. **Anda dapat mendaftarkan skripsi**.", source:"Peraturan Akademik UNILA 2025 Pasal 67 ayat (1) huruf a" },
    { rule_id:"R018", category:"Skripsi", priority:2, conditions:[{field:"sks_lulus",op:"<",val:80}], result:{boleh_skripsi:false}, template:"SKS lulus {sks_lulus} < 80. **Belum memenuhi syarat** pengajuan skripsi. Selesaikan minimal 80 SKS terlebih dahulu.", source:"Peraturan Akademik UNILA 2025 Pasal 67 ayat (1) huruf a" },
    { rule_id:"R019", category:"Skripsi", priority:1, conditions:[{field:"ipk",op:"<",val:2.0}], result:{boleh_skripsi:false}, template:"IPK {ipk} < 2.00. **Belum memenuhi syarat IPK** untuk pengajuan skripsi. Tingkatkan IPK minimal menjadi 2.00.", source:"Peraturan Akademik UNILA 2025" },
    { rule_id:"R020", category:"Skripsi", priority:1, conditions:[{field:"kkn",op:"==",val:true}], result:{syarat_kkn_skripsi:true}, template:"KKN wajib diselesaikan atau berjalan bersamaan sebelum **sidang skripsi**. Pastikan status KKN Anda sudah lunas.", source:"Peraturan Akademik UNILA 2025" },
    { rule_id:"R021", category:"Skripsi", priority:1, conditions:[{field:"pkl",op:"==",val:true}], result:{syarat_pkl_skripsi:true}, template:"PKL/Magang wajib diselesaikan sebelum pengajuan skripsi bagi program studi yang mewajibkan PKL.", source:"Peraturan Akademik UNILA 2025" },
    { rule_id:"R022", category:"Skripsi", priority:1, conditions:[], result:{batas_revisi:true}, template:"Revisi skripsi pasca-sidang wajib diselesaikan dalam **30 hari kerja**. Lewat batas, mahasiswa harus sidang ulang.", source:"Peraturan Akademik UNILA 2025" },

    // === KKN (KULIAH KERJA NYATA) ===
    { rule_id:"R023A", category:"KKN", priority:0, conditions:[], result:{info_syarat_kkn:true}, template:"📌 **Syarat mengikuti KKN UNILA (umum)**\n\nAgar bisa mendaftar KKN, umumnya mahasiswa harus memenuhi:\n• **SKS lulus minimal 100 SKS**\n• **IPK minimal 2.00**\n• **Minimal semester 6**\n• Status akademik aktif dan **administrasi/UKT semester berjalan lunas** (sesuai ketentuan pendaftaran)\n\nJika Anda kirim data: **SKS lulus, IPK, dan semester**, saya bisa cek apakah Anda **sudah memenuhi** syaratnya.", source:"Panduan KKN UNILA 2024" },
    { rule_id:"R023", category:"KKN", priority:1, conditions:[{field:"sks_lulus",op:">=",val:100},{field:"ipk",op:">=",val:2.0},{field:"semester",op:">=",val:6}], result:{boleh_kkn:true}, template:"✅ **Syarat KKN terpenuhi!**\n\n**Persyaratan yang sudah dipenuhi:**\n• SKS lulus: {sks_lulus} ≥ 100 ✓\n• IPK: {ipk} ≥ 2.00 ✓\n• Semester: {semester} ≥ 6 ✓\n\n**Anda dapat mendaftar KKN** pada periode pendaftaran berikutnya.", source:"Panduan KKN UNILA 2024" },
    { rule_id:"R024", category:"KKN", priority:2, conditions:[{field:"sks_lulus",op:"<",val:100}], result:{boleh_kkn:false}, template:"❌ **Belum memenuhi syarat KKN**\n\nSKS lulus Anda: **{sks_lulus} SKS**\nSyarat minimal: **100 SKS**\nKekurangan: **{100-sks_lulus} SKS**\n\nSelesaikan mata kuliah hingga mencapai 100 SKS terlebih dahulu.", source:"Panduan KKN UNILA 2024" },
    { rule_id:"R025", category:"KKN", priority:2, conditions:[{field:"semester",op:"<",val:6}], result:{boleh_kkn:false}, template:"❌ **Belum memenuhi syarat semester untuk KKN**\n\nSemester Anda saat ini: **Semester {semester}**\nSyarat minimal: **Semester 6**\n\nKKN dapat diikuti mulai semester 6 ke atas.", source:"Panduan KKN UNILA 2024" },
    { rule_id:"R026", category:"KKN", priority:1, conditions:[], result:{kkn_sks:true}, template:"📚 **Informasi Bobot SKS KKN**\n\nKKN memberikan bobot **3 SKS** yang akan diperhitungkan dalam:\n• Transkrip akademik\n• Total SKS kelulusan\n• Perhitungan IPK\n\nNilai KKN: A, B+, B, C+, C, D, atau E", source:"Panduan KKN UNILA 2024" },
    { rule_id:"R026A", category:"KKN", priority:1, conditions:[], result:{kkn_durasi:true}, template:"⏱️ **Durasi Pelaksanaan KKN**\n\nKKN dilaksanakan selama **30-45 hari** (1-1.5 bulan) di lokasi yang ditentukan oleh LP2M UNILA.\n\n**Tahapan:**\n1. Pembekalan (3-5 hari)\n2. Pelaksanaan di lokasi (30-45 hari)\n3. Pelaporan dan evaluasi (7 hari)", source:"Panduan KKN UNILA 2024" },
    { rule_id:"R026B", category:"KKN", priority:1, conditions:[], result:{kkn_biaya:true}, template:"💰 **Biaya KKN**\n\nBiaya KKN **sudah termasuk dalam UKT** semester berjalan. Tidak ada biaya tambahan untuk:\n• Pendaftaran KKN\n• Pembekalan\n• Sertifikat\n\nBiaya tambahan yang mungkin timbul:\n• Transportasi ke lokasi (ditanggung mahasiswa)\n• Akomodasi dan konsumsi selama di lokasi", source:"Panduan KKN UNILA 2024" },
    { rule_id:"R026C", category:"KKN", priority:1, conditions:[], result:{kkn_dokumen:true}, template:"📄 **Dokumen yang Diperlukan untuk Pendaftaran KKN**\n\n1. Formulir pendaftaran KKN (dari LP2M)\n2. Fotokopi KTM yang masih berlaku\n3. Transkrip nilai sementara (min. 100 SKS)\n4. Surat keterangan sehat dari dokter\n5. Pas foto 3x4 (2 lembar)\n6. Bukti pembayaran UKT semester berjalan\n7. Surat persetujuan orang tua/wali", source:"Panduan KKN UNILA 2024" },
    { rule_id:"R026D", category:"KKN", priority:1, conditions:[], result:{kkn_lokasi:true}, template:"📍 **Penempatan Lokasi KKN**\n\nLokasi KKN ditentukan oleh **LP2M UNILA** berdasarkan:\n• Kebutuhan masyarakat\n• Pemerataan wilayah\n• Keamanan lokasi\n• Aksesibilitas\n\n**Catatan:** Mahasiswa tidak dapat memilih lokasi sendiri, kecuali ada program KKN mandiri dengan persetujuan khusus.", source:"Panduan KKN UNILA 2024" },

    // === PKL / MAGANG / KERJA PRAKTIK ===
    { rule_id:"R027A", category:"PKL", priority:0, conditions:[], result:{info_syarat_pkl:true}, template:"📌 **Syarat mengikuti PKL/Magang/KP UNILA (umum)**\n\nAgar bisa mendaftar PKL/Magang/Kerja Praktik, umumnya mahasiswa harus memenuhi:\n• **SKS lulus minimal 80 SKS**\n• **Minimal semester 5**\n• Status akademik aktif dan memenuhi ketentuan program studi\n\nJika Anda kirim data: **SKS lulus dan semester**, saya bisa cek apakah Anda **sudah memenuhi** syaratnya.", source:"Panduan PKL UNILA 2024" },
    { rule_id:"R027", category:"PKL", priority:1, conditions:[{field:"sks_lulus",op:">=",val:80},{field:"semester",op:">=",val:5}], result:{boleh_pkl:true}, template:"✅ **Syarat PKL/Magang terpenuhi!**\n\n**Persyaratan yang sudah dipenuhi:**\n• SKS lulus: {sks_lulus} ≥ 80 ✓\n• Semester: {semester} ≥ 5 ✓\n\n**Langkah selanjutnya:**\n1. Konsultasi dengan dosen pembimbing PKL\n2. Cari tempat magang/instansi\n3. Ajukan proposal PKL ke program studi\n4. Dapatkan surat pengantar dari fakultas", source:"Panduan PKL UNILA 2024" },
    { rule_id:"R028", category:"PKL", priority:2, conditions:[{field:"sks_lulus",op:"<",val:80}], result:{boleh_pkl:false}, template:"❌ **Belum memenuhi syarat PKL**\n\nSKS lulus Anda: **{sks_lulus} SKS**\nSyarat minimal: **80 SKS**\nKekurangan: **{80-sks_lulus} SKS**\n\nSelesaikan mata kuliah hingga mencapai 80 SKS terlebih dahulu.", source:"Panduan PKL UNILA 2024" },
    { rule_id:"R029", category:"PKL", priority:1, conditions:[], result:{pkl_durasi:true}, template:"⏱️ **Durasi PKL/Magang**\n\nPKL dilaksanakan selama **minimal 1 bulan (4 minggu kerja efektif)** atau **160 jam kerja** di instansi/perusahaan.\n\n**Catatan:**\n• Hari libur/weekend tidak dihitung\n• Beberapa program studi mensyaratkan 2-3 bulan\n• Durasi dapat disesuaikan dengan kebijakan instansi", source:"Panduan PKL UNILA 2024" },
    { rule_id:"R029A", category:"PKL", priority:1, conditions:[], result:{pkl_sks:true}, template:"📚 **Bobot SKS PKL**\n\nPKL memberikan bobot **2-4 SKS** tergantung program studi:\n• Teknik: 3-4 SKS\n• Ekonomi/Bisnis: 2-3 SKS\n• MIPA: 2-3 SKS\n• Pertanian: 3-4 SKS\n• Ilmu Sosial: 2 SKS\n\nNilai PKL diperhitungkan dalam IPK.", source:"Panduan PKL UNILA 2024" },
    { rule_id:"R029B", category:"PKL", priority:1, conditions:[], result:{pkl_tempat:true}, template:"🏢 **Tempat PKL yang Direkomendasikan**\n\n**Instansi Pemerintah:**\n• Kementerian/Lembaga\n• Pemerintah Daerah\n• BUMN/BUMD\n\n**Swasta:**\n• Perusahaan nasional/multinasional\n• Startup teknologi\n• Industri manufaktur\n• Perbankan dan keuangan\n\n**Syarat:** Instansi harus relevan dengan bidang studi dan disetujui program studi.", source:"Panduan PKL UNILA 2024" },
    { rule_id:"R029C", category:"PKL", priority:1, conditions:[], result:{pkl_dokumen:true}, template:"📄 **Dokumen PKL yang Diperlukan**\n\n**Sebelum PKL:**\n1. Proposal PKL\n2. Surat pengantar dari fakultas\n3. CV dan transkrip nilai\n4. Surat persetujuan instansi\n\n**Setelah PKL:**\n1. Laporan PKL (buku)\n2. Logbook kegiatan harian\n3. Sertifikat/surat keterangan dari instansi\n4. Lembar penilaian dari pembimbing lapangan\n5. Form penilaian dari dosen pembimbing", source:"Panduan PKL UNILA 2024" },
    { rule_id:"R029D", category:"PKL", priority:1, conditions:[], result:{pkl_pembimbing:true}, template:"👨‍🏫 **Pembimbingan PKL**\n\nSetiap mahasiswa PKL mendapat **2 pembimbing:**\n\n1. **Dosen Pembimbing** (dari kampus)\n   • Membimbing penyusunan proposal dan laporan\n   • Melakukan monitoring\n   • Menilai laporan akhir\n\n2. **Pembimbing Lapangan** (dari instansi)\n   • Membimbing kegiatan di lapangan\n   • Menilai kinerja harian\n   • Memberikan sertifikat/penilaian", source:"Panduan PKL UNILA 2024" },
    { rule_id:"R029E", category:"PKL", priority:1, conditions:[], result:{pkl_biaya:true}, template:"💰 **Biaya PKL**\n\nBiaya PKL **sudah termasuk dalam UKT** semester berjalan.\n\n**Biaya tambahan yang mungkin timbul:**\n• Transportasi ke lokasi PKL (ditanggung mahasiswa)\n• Akomodasi jika di luar kota\n• Penjilidan laporan PKL\n• Fotokopi dokumen\n\n**Catatan:** Beberapa instansi memberikan uang saku/transport untuk peserta PKL.", source:"Panduan PKL UNILA 2024" },

    // === YUDISIUM ===
    { rule_id:"R030", category:"Yudisium", priority:1, conditions:[{field:"sks_lulus",op:">=",val:144},{field:"ipk",op:">=",val:2.0},{field:"skripsi",op:"==",val:true},{field:"kkn",op:"==",val:true}], result:{boleh_yudisium:true}, template:"Semua syarat yudisium terpenuhi (SKS ≥144, IPK ≥2.00, skripsi lulus, KKN selesai). **Anda dapat mendaftar yudisium**.", source:"Peraturan Akademik UNILA 2025 Pasal 76" },
    { rule_id:"R031", category:"Yudisium", priority:2, conditions:[{field:"sks_lulus",op:"<",val:144}], result:{boleh_yudisium:false}, template:"SKS lulus {sks_lulus} < 144. **Belum memenuhi syarat yudisium**. Selesaikan seluruh beban SKS program studi.", source:"Peraturan Akademik UNILA 2025 Pasal 42" },
    { rule_id:"R032", category:"Yudisium", priority:1, conditions:[{field:"ipk",op:">",val:3.50},{field:"sks_lulus",op:">=",val:144}], result:{predikat:"Dengan Pujian (Cum Laude)"}, template:"IPK {ipk} > 3.50 dengan SKS ≥144 dan lulus ≤8 semester. Predikat kelulusan: **Dengan Pujian (Cum Laude)** 🏆", source:"Peraturan Akademik UNILA 2025 Pasal 77" },
    { rule_id:"R033", category:"Yudisium", priority:2, conditions:[{field:"ipk",op:">=",val:3.01},{field:"ipk",op:"<=",val:3.50}], result:{predikat:"Sangat Memuaskan"}, template:"IPK {ipk} antara 3.01–3.50. Predikat kelulusan: **Sangat Memuaskan** ✨", source:"Peraturan Akademik UNILA 2025 Pasal 77" },
    { rule_id:"R034", category:"Yudisium", priority:3, conditions:[{field:"ipk",op:">=",val:2.76},{field:"ipk",op:"<",val:3.01}], result:{predikat:"Memuaskan"}, template:"IPK {ipk} antara 2.76–3.00. Predikat kelulusan: **Memuaskan**.", source:"Peraturan Akademik UNILA 2025 Pasal 77" },
    { rule_id:"R035", category:"Yudisium", priority:4, conditions:[{field:"ipk",op:">=",val:2.0},{field:"ipk",op:"<",val:2.76}], result:{predikat:"Cukup"}, template:"IPK {ipk} antara 2.00–2.75. Predikat kelulusan: **Cukup**.", source:"Peraturan Akademik UNILA 2025 Pasal 77" },

    // === WISUDA ===
    { rule_id:"R036", category:"Wisuda", priority:1, conditions:[{field:"yudisium",op:"==",val:true}], result:{boleh_wisuda:true}, template:"Setelah yudisium dinyatakan lulus, **Anda berhak mendaftar wisuda** pada periode wisuda berikutnya.", source:"Peraturan Akademik UNILA 2025 Bab X" },
    { rule_id:"R037", category:"Wisuda", priority:1, conditions:[], result:{wisuda_periode:true}, template:"Wisuda UNILA diselenggarakan **2-3 kali per tahun**. Jadwal wisuda diumumkan melalui website resmi UNILA.", source:"Peraturan Akademik UNILA 2025 Bab X" },
    { rule_id:"R038", category:"Wisuda", priority:1, conditions:[], result:{dokumen_wisuda:true}, template:"Dokumen wisuda yang diperlukan: ijazah sementara, pas foto resmi, kwitansi pembayaran wisuda, dan formulir pendaftaran wisuda dari BAAK.", source:"Peraturan Akademik UNILA 2025 Bab X" },

    // === REGISTRASI & HERREGISTRASI ===
    { rule_id:"R039", category:"Registrasi", priority:1, conditions:[], result:{waktu_registrasi:true}, template:"📅 **Jadwal Registrasi/Herregistrasi**\n\nRegistrasi dilakukan pada **awal setiap semester** sesuai kalender akademik UNILA:\n\n**Semester Ganjil:** Biasanya Agustus\n**Semester Genap:** Biasanya Februari\n\n⚠️ **Penting:** Mahasiswa yang tidak herregistrasi dianggap **cuti paksa** dan tidak dapat mengikuti perkuliahan.", source:"Peraturan Akademik UNILA 2025 Bab III Pasal 8" },
    { rule_id:"R040", category:"Registrasi", priority:1, conditions:[{field:"administrasi",op:"==",val:false}], result:{tidak_bisa_registrasi:true}, template:"❌ **Administrasi Belum Lunas**\n\nAnda **tidak dapat melakukan herregistrasi** karena administrasi belum lunas.\n\n**Langkah yang harus dilakukan:**\n1. Cek tagihan UKT di portal keuangan UNILA\n2. Lakukan pembayaran melalui bank yang ditunjuk\n3. Tunggu verifikasi pembayaran (1x24 jam)\n4. Lakukan herregistrasi online di SIAKAD\n\n📞 **Hubungi:** BAAK Fakultas atau Bagian Keuangan UNILA", source:"Peraturan Akademik UNILA 2025 Bab III Pasal 9" },
    { rule_id:"R041", category:"Registrasi", priority:1, conditions:[], result:{krs_online:true}, template:"💻 **Pengisian KRS Online**\n\nPengisian KRS dilakukan secara **online melalui SIAKAD UNILA** (siakad.unila.ac.id)\n\n**Tahapan:**\n1. Login ke SIAKAD dengan NIM dan password\n2. Pilih menu 'Pengisian KRS'\n3. Pilih mata kuliah sesuai kurikulum\n4. Perhatikan batas maksimal SKS berdasarkan IPK\n5. Konsultasi dengan Pembimbing Akademik (PA)\n6. Submit KRS dan cetak KRS\n\n**Masa pengisian:** Sesuai kalender akademik (biasanya 1-2 minggu di awal semester)", source:"Peraturan Akademik UNILA 2025 Bab IV Pasal 14" },
    { rule_id:"R041A", category:"Registrasi", priority:1, conditions:[], result:{perubahan_krs:true}, template:"✏️ **Perubahan KRS (PKRS)**\n\nPerubahan/pembatalan KRS dapat dilakukan pada masa **PKRS** (Perubahan KRS):\n\n**Waktu:** 1-2 minggu setelah perkuliahan dimulai\n**Operasi yang bisa dilakukan:**\n• Menambah mata kuliah\n• Membatalkan mata kuliah (drop)\n• Mengubah kelas\n\n⚠️ **Catatan:**\n• Setelah masa PKRS, KRS tidak dapat diubah\n• Pembatalan setelah UTS akan mendapat nilai E\n• Perubahan harus disetujui PA", source:"Peraturan Akademik UNILA 2025 Bab IV Pasal 16" },
    { rule_id:"R041B", category:"Registrasi", priority:1, conditions:[], result:{herregistrasi_syarat:true}, template:"✅ **Syarat Herregistrasi**\n\nUntuk dapat melakukan herregistrasi, mahasiswa harus:\n\n1. **Administrasi Keuangan Lunas**\n   • UKT semester sebelumnya lunas\n   • Tidak ada tunggakan biaya lain\n\n2. **Status Akademik Aktif**\n   • Tidak sedang cuti\n   • Tidak dalam status DO\n   • Tidak sedang skorsing\n\n3. **Dokumen Lengkap**\n   • KTM masih berlaku\n   • Data di SIAKAD ter-update\n\n4. **Persetujuan PA**\n   • Konsultasi dengan Pembimbing Akademik", source:"Peraturan Akademik UNILA 2025 Bab III Pasal 8" },

    // === DROP OUT (DO) ===
    { rule_id:"R042", category:"DO", priority:1, conditions:[{field:"semester",op:">",val:14},{field:"sks_lulus",op:"<",val:144}], result:{resiko_do:true}, template:"⚠️ **Peringatan DO:** Semester {semester} telah melewati batas 14 semester tanpa menyelesaikan studi. Konsultasikan segera dengan Pembimbing Akademik.", source:"Peraturan Akademik UNILA 2025 Pasal 48" },
    { rule_id:"R043", category:"DO", priority:2, conditions:[{field:"ipk",op:"<",val:2.0},{field:"semester",op:">=",val:4}], result:{peringatan_do:true}, template:"⚠️ **IPK {ipk} di bawah 2.00 pada semester {semester}.** Anda mendapat peringatan akademik. Jika tidak meningkat hingga akhir semester ini, berisiko dikenakan DO.", source:"Peraturan Akademik UNILA 2025 Pasal 48" },
    { rule_id:"R044", category:"DO", priority:1, conditions:[{field:"tidak_herregistrasi",op:">=",val:2}], result:{do_administrasi:true}, template:"Tidak melakukan herregistrasi **2 semester berturut-turut** mengakibatkan mahasiswa dikeluarkan (DO) secara administratif.", source:"Peraturan Akademik UNILA 2025 Pasal 48" },
    { rule_id:"R045", category:"DO", priority:1, conditions:[], result:{batas_studi:true}, template:"Batas maksimal masa studi di UNILA adalah **14 semester** (7 tahun) untuk program S1. Tidak termasuk masa cuti yang diizinkan.", source:"Peraturan Akademik UNILA 2025 Pasal 48" },

    // === CUTI AKADEMIK ===
    { rule_id:"R046", category:"Cuti", priority:1, conditions:[{field:"semester",op:">=",val:2}], result:{boleh_cuti:true}, template:"Mahasiswa mulai **semester 2** dapat mengajukan cuti akademik dengan persetujuan Dekan.", source:"Peraturan Akademik UNILA 2025 Pasal 47" },
    { rule_id:"R047", category:"Cuti", priority:1, conditions:[], result:{max_cuti:true}, template:"Cuti akademik diizinkan maksimal **2 semester** (tidak berturut-turut). Masa cuti tidak dihitung dalam batas studi.", source:"Peraturan Akademik UNILA 2025 Pasal 47" },
    { rule_id:"R048", category:"Cuti", priority:1, conditions:[{field:"semester",op:"==",val:1}], result:{boleh_cuti:false}, template:"Mahasiswa **semester 1 tidak diperkenankan** mengajukan cuti akademik.", source:"Peraturan Akademik UNILA 2025 Pasal 47" },
    { rule_id:"R049", category:"Cuti", priority:1, conditions:[], result:{prosedur_cuti:true}, template:"Prosedur cuti: (1) Isi formulir cuti di BAAK, (2) Persetujuan PA dan Ketua Program Studi, (3) Persetujuan Dekan, (4) Surat Keputusan Rektor.", source:"Peraturan Akademik UNILA 2025 Pasal 47" },
    { rule_id:"R050", category:"Cuti", priority:1, conditions:[], result:{ukt_cuti:true}, template:"Selama cuti akademik, mahasiswa dibebaskan dari kewajiban membayar UKT penuh namun mungkin dikenakan biaya administrasi cuti.", source:"Peraturan Akademik UNILA 2025 Pasal 47" },

    // === IPK TAMBAHAN ===
    { rule_id:"R051", category:"IPK", priority:1, conditions:[{field:"ipk",op:">",val:3.50}], result:{status_ipk:"Sangat Baik (Cum Laude)"}, template:"IPK {ipk} termasuk kategori **Sangat Baik** dan memenuhi predikat Cum Laude jika menyelesaikan studi ≤8 semester.", source:"Peraturan Akademik UNILA 2025 Pasal 77" },
    { rule_id:"R052", category:"IPK", priority:2, conditions:[{field:"ipk",op:">=",val:3.0},{field:"ipk",op:"<",val:3.51}], result:{status_ipk:"Baik"}, template:"IPK {ipk} termasuk kategori **Baik**. Pertahankan dan tingkatkan untuk meraih predikat Cum Laude.", source:"Peraturan Akademik UNILA 2025 Pasal 77" },
    { rule_id:"R053", category:"IPK", priority:3, conditions:[{field:"ipk",op:">=",val:2.0},{field:"ipk",op:"<",val:3.0}], result:{status_ipk:"Cukup"}, template:"IPK {ipk} termasuk kategori **Cukup**. Upayakan peningkatan IPK untuk memperluas kesempatan SKS dan kelulusan.", source:"Peraturan Akademik UNILA 2025 Pasal 77" },
    { rule_id:"R054", category:"IPK", priority:4, conditions:[{field:"ipk",op:"<",val:2.0}], result:{status_ipk:"Kurang - Perlu Bimbingan"}, template:"⚠️ IPK {ipk} di bawah 2.00. Status: **Perlu Bimbingan**. Segera konsultasikan dengan Pembimbing Akademik (PA) Anda.", source:"Peraturan Akademik UNILA 2025 Pasal 48" },

    // === NILAI AKADEMIK ===
    { rule_id:"R055", category:"Nilai", priority:1, conditions:[], result:{skala_nilai:true}, template:"Skala nilai UNILA: A (4.0/≥76), B+ (3.5/71-75,99), B (3.0/66-70,99), C+ (2.5/61-65,99), C (2.0/56-60,99), D (1.0/50-55,99), E (0.0/<50).", source:"Peraturan Akademik UNILA 2025 Pasal 41 ayat (3)" },
    { rule_id:"R056", category:"Nilai", priority:1, conditions:[], result:{nilai_minimal_lulus:true}, template:"Nilai minimal **lulus** untuk suatu mata kuliah adalah C (2.0). Nilai D dan E dinyatakan tidak lulus dan harus diulang.", source:"Peraturan Akademik UNILA 2025 Bab V Pasal 18" },
    { rule_id:"R057", category:"Nilai", priority:1, conditions:[], result:{perbaikan_nilai:true}, template:"Perbaikan nilai hanya bisa dilakukan pada **Semester Pendek atau semester regular** dengan mendaftar ulang mata kuliah tersebut. Nilai tertinggi yang berlaku.", source:"Peraturan Akademik UNILA 2025 Bab V Pasal 19" },
    { rule_id:"R058", category:"Nilai", priority:1, conditions:[], result:{transkrip:true}, template:"Transkrip sementara dapat dicetak mandiri melalui **SIAKAD UNILA**. Transkrip resmi diterbitkan oleh BAAK dengan tanda tangan Dekan/Rektor.", source:"Peraturan Akademik UNILA 2025 Bab V Pasal 20" },

    // === PEMBIMBING AKADEMIK ===
    { rule_id:"R059", category:"PA", priority:1, conditions:[], result:{fungsi_pa:true}, template:"Pembimbing Akademik (PA) bertugas membimbing mahasiswa dalam: perencanaan studi, pemilihan mata kuliah, penyelesaian masalah akademik, dan konsultasi permasalahan studi.", source:"Peraturan Akademik UNILA 2025 Bab II Pasal 6" },
    { rule_id:"R060", category:"PA", priority:1, conditions:[], result:{konsultasi_pa:true}, template:"Konsultasi dengan PA dilakukan **minimal 2 kali per semester**: awal semester (pengisian KRS) dan akhir semester (evaluasi hasil studi).", source:"Peraturan Akademik UNILA 2025 Bab II Pasal 7" },

    // === UKT & KEUANGAN ===
    { rule_id:"R061", category:"Keuangan", priority:1, conditions:[], result:{ukt_info:true}, template:"UKT (Uang Kuliah Tunggal) dibayarkan **satu kali per semester** sesuai golongan yang telah ditetapkan saat seleksi masuk. UKT tidak berubah selama studi normal.", source:"Peraturan Akademik UNILA 2025 Bab III Pasal 10" },
    { rule_id:"R062", category:"Keuangan", priority:1, conditions:[], result:{cicilan_ukt:true}, template:"Mahasiswa yang kesulitan membayar UKT dapat mengajukan **keringanan atau cicilan UKT** melalui Direktorat Kemahasiswaan UNILA dengan melampirkan dokumen pendukung.", source:"Peraturan Akademik UNILA 2025 Bab III Pasal 11" },
    { rule_id:"R063", category:"Keuangan", priority:1, conditions:[], result:{beasiswa:true}, template:"UNILA menyediakan berbagai beasiswa: KIP-K, Bidikmisi, beasiswa prestasi, beasiswa Peningkatan Prestasi Akademik (PPA), dan beasiswa dari mitra industri.", source:"Peraturan Akademik UNILA 2025 Bab III Pasal 12" },

    // === ADMINISTRASI AKADEMIK ===
    { rule_id:"R064", category:"Administrasi", priority:1, conditions:[], result:{surat_keterangan:true}, template:"Surat keterangan mahasiswa aktif dapat diajukan ke **BAAK Fakultas** dengan membawa KTM dan bukti herregistrasi semester berjalan.", source:"Peraturan Akademik UNILA 2025 Bab XIII Pasal 80" },
    { rule_id:"R065", category:"Administrasi", priority:1, conditions:[], result:{ktm:true}, template:"KTM (Kartu Tanda Mahasiswa) diterbitkan saat pertama kali registrasi. KTM yang hilang dapat diurus melalui BAAK dengan membawa laporan kehilangan dari kepolisian.", source:"Peraturan Akademik UNILA 2025 Bab XIII Pasal 81" },
    { rule_id:"R066", category:"Administrasi", priority:1, conditions:[], result:{legalisir:true}, template:"Legalisir dokumen akademik dilakukan di **BAAK Fakultas** masing-masing. Biaya legalisir sesuai ketentuan yang berlaku.", source:"Peraturan Akademik UNILA 2025 Bab XIII Pasal 82" },

    // === PINDAH PROGRAM STUDI ===
    { rule_id:"R067", category:"PindahProdi", priority:1, conditions:[{field:"semester",op:">=",val:2},{field:"semester",op:"<=",val:4}], result:{boleh_pindah_prodi:true}, template:"Perpindahan program studi dapat diajukan pada **semester 2-4** dengan memenuhi syarat akademik program studi tujuan.", source:"Peraturan Akademik UNILA 2025 Bab XIV Pasal 85" },
    { rule_id:"R068", category:"PindahProdi", priority:2, conditions:[{field:"semester",op:">",val:4}], result:{boleh_pindah_prodi:false}, template:"Semester {semester} > 4. **Perpindahan program studi tidak dimungkinkan** setelah melewati semester 4.", source:"Peraturan Akademik UNILA 2025 Bab XIV Pasal 85" },

    // === MAHASISWA ASING ===
    { rule_id:"R069", category:"MahasiswaAsing", priority:1, conditions:[], result:{ekuivalensi:true}, template:"Mahasiswa transfer/asing wajib mengikuti proses **ekuivalensi mata kuliah** yang diproses oleh Tim Akademik Fakultas sebelum semester pertama.", source:"Peraturan Akademik UNILA 2025 Bab XV Pasal 90" },

    // === PELAKSANAAN UJIAN ===
    { rule_id:"R070", category:"Ujian", priority:1, conditions:[], result:{tata_tertib_ujian:true}, template:"Selama ujian: wajib membawa KTM, hadir tepat waktu, tidak mencontek, mematikan HP, dan mematuhi semua tata tertib ruang ujian.", source:"Peraturan Akademik UNILA 2025 Bab VI Pasal 24" },
    { rule_id:"R071", category:"Ujian", priority:1, conditions:[], result:{keterlambatan_ujian:true}, template:"Mahasiswa yang terlambat lebih dari **30 menit** tidak diizinkan mengikuti ujian. Hadir tepat waktu adalah kewajiban.", source:"Peraturan Akademik UNILA 2025 Bab VI Pasal 23" },
    { rule_id:"R072", category:"Ujian", priority:1, conditions:[], result:{kecurangan_ujian:true}, template:"Mahasiswa yang terbukti melakukan kecurangan dalam ujian akan mendapat nilai **E (nol)** dan dapat dikenakan sanksi akademik lebih lanjut.", source:"Peraturan Akademik UNILA 2025 Bab VI Pasal 25" },

    // === BEBAN STUDI TAMBAHAN ===
    { rule_id:"R073", category:"SKS", priority:1, conditions:[{field:"semester",op:">=",val:7},{field:"ipk",op:">=",val:3.0},{field:"sks_lulus",op:">=",val:100}], result:{boleh_24_sks:true}, template:"Semester {semester} dengan IPK ≥3.00 dan SKS lulus ≥100: **Anda layak mengambil 24 SKS** untuk percepatan kelulusan.", source:"Peraturan Akademik UNILA 2025 Bab IV Pasal 15" },
    { rule_id:"R074", category:"SKS", priority:1, conditions:[], result:{min_sks_lulus:true}, template:"Total SKS yang harus diselesaikan untuk lulus S1 di UNILA umumnya antara **144-160 SKS** tergantung program studi.", source:"Peraturan Akademik UNILA 2025 Bab IV Pasal 11" },

    // === PROGRAM MERDEKA BELAJAR ===
    { rule_id:"R075", category:"MBKM", priority:1, conditions:[{field:"semester",op:">=",val:5},{field:"ipk",op:">=",val:2.5}], result:{boleh_mbkm:true}, template:"Mahasiswa semester ≥5 dengan IPK ≥2.50 dapat mengikuti program **Merdeka Belajar-Kampus Merdeka (MBKM)** seperti magang, studi independen, atau pertukaran mahasiswa.", source:"Panduan MBKM UNILA 2022" },
    { rule_id:"R076", category:"MBKM", priority:1, conditions:[], result:{sks_mbkm:true}, template:"Kegiatan MBKM dapat dikonversi hingga **20 SKS** per semester, setara dengan beban studi reguler penuh.", source:"Panduan MBKM UNILA 2022 Pasal 5" },
    { rule_id:"R077", category:"MBKM", priority:1, conditions:[], result:{jenis_mbkm:true}, template:"Jenis kegiatan MBKM yang diakui: (1) Magang/Praktik Kerja, (2) Studi/Proyek Independen, (3) Pertukaran Mahasiswa, (4) Asistensi Mengajar, (5) Proyek Kemanusiaan, (6) Wirausaha, (7) KKN Tematik.", source:"Panduan MBKM UNILA 2022 Pasal 3" },

    // === KALENDER AKADEMIK ===
    { rule_id:"R078", category:"Kalender", priority:1, conditions:[], result:{semester_ganjil:true}, template:"Semester Ganjil berlangsung antara **bulan Agustus hingga Januari**. Registrasi, perkuliahan, UTS, UAS, dan pengumuman nilai dilaksanakan dalam periode ini.", source:"Kalender Akademik UNILA" },
    { rule_id:"R079", category:"Kalender", priority:1, conditions:[], result:{semester_genap:true}, template:"Semester Genap berlangsung antara **bulan Februari hingga Juli**. Semester Pendek biasanya diselenggarakan pada bulan Juli-Agustus.", source:"Kalender Akademik UNILA" },

    // === ETIKA AKADEMIK ===
    { rule_id:"R080", category:"Etika", priority:1, conditions:[], result:{plagiarisme:true}, template:"Plagiarisme dalam tugas, laporan, atau skripsi dikenakan sanksi berat: nilai nol, pengulangan mata kuliah, hingga **pencabutan gelar**. Gunakan software anti-plagiat seperti Turnitin.", source:"Peraturan Akademik UNILA 2025 Bab XVI Pasal 95" },
    { rule_id:"R081", category:"Etika", priority:1, conditions:[], result:{etika_kampus:true}, template:"Mahasiswa UNILA wajib menjaga etika akademik: jujur dalam ujian, menghormati dosen dan civitas akademika, berpakaian sopan, dan menjaga nama baik universitas.", source:"Peraturan Akademik UNILA 2025 Bab XVI Pasal 94" },

    // === ORIENTASI & PENGENALAN ===
    { rule_id:"R082", category:"Orientasi", priority:1, conditions:[{field:"semester",op:"==",val:1}], result:{pkkmb:true}, template:"Mahasiswa baru semester 1 wajib mengikuti **PKKMB (Pengenalan Kehidupan Kampus Mahasiswa Baru)** sebagai syarat aktivasi status mahasiswa.", source:"Peraturan Akademik UNILA 2025 Bab I Pasal 3" },

    // === GELAR & IJAZAH ===
    { rule_id:"R083", category:"Ijazah", priority:1, conditions:[{field:"yudisium",op:"==",val:true}], result:{ijazah_info:true}, template:"Ijazah dan transkrip resmi diterbitkan **1-3 bulan** setelah yudisium. Sementara menunggu, gunakan Surat Keterangan Lulus (SKL) untuk keperluan administrasi.", source:"Peraturan Akademik UNILA 2025 Bab XI Pasal 73" },
    { rule_id:"R084", category:"Ijazah", priority:1, conditions:[], result:{gelar:true}, template:"Gelar akademik untuk program S1 UNILA: **Sarjana (S.xxx)** sesuai bidang ilmu. Contoh: S.T (Teknik), S.E (Ekonomi), S.H (Hukum), dll.", source:"Peraturan Akademik UNILA 2025 Bab XI Pasal 68" },

    // === SKRIPSI LANJUTAN ===
    { rule_id:"R085", category:"Skripsi", priority:1, conditions:[], result:{seminar_proposal:true}, template:"Sebelum penelitian skripsi, mahasiswa wajib melaksanakan **Seminar Proposal** yang dihadiri minimal 10 mahasiswa aktif dan disetujui pembimbing.", source:"Peraturan Akademik UNILA 2025 Bab IX Pasal 47" },
    { rule_id:"R086", category:"Skripsi", priority:1, conditions:[], result:{sidang_skripsi:true}, template:"Sidang Skripsi (Ujian Komprehensif) dilaksanakan di hadapan **3-5 penguji**. Nilai sidang adalah gabungan penilaian seluruh penguji.", source:"Peraturan Akademik UNILA 2025 Bab IX Pasal 48" },
    { rule_id:"R087", category:"Skripsi", priority:1, conditions:[], result:{pembimbing_skripsi:true}, template:"Setiap mahasiswa berhak mendapat **2 dosen pembimbing skripsi**: Pembimbing I (ahli bidang utama) dan Pembimbing II (ahli bidang pendukung/metodologi).", source:"Peraturan Akademik UNILA 2025 Bab IX Pasal 44" },

    // === PROGRAM DOKTOR/MAGISTER (REFERENSI) ===
    { rule_id:"R088", category:"Pascasarjana", priority:1, conditions:[], result:{s2_info:true}, template:"Program Magister (S2) UNILA memiliki beban studi 36-48 SKS dengan masa studi maksimal **8 semester (4 tahun)**.", source:"Panduan Akademik Pascasarjana UNILA" },
    { rule_id:"R089", category:"Pascasarjana", priority:1, conditions:[], result:{s3_info:true}, template:"Program Doktor (S3) UNILA memiliki beban studi 42-48 SKS dengan masa studi maksimal **10 semester (5 tahun)**.", source:"Panduan Akademik Pascasarjana UNILA" },

    // === EKUIVALENSI & KONVERSI ===
    { rule_id:"R090", category:"Ekuivalensi", priority:1, conditions:[], result:{ekuivalensi_info:true}, template:"Konversi nilai dari skala 100 ke 4.0: 85-100→A(4.0), 80-84→B+(3.5), 70-79→B(3.0), 65-69→C+(2.5), 56-64→C(2.0), 41-55→D(1.0), 0-40→E(0).", source:"Peraturan Akademik UNILA 2025 Pasal 41 ayat (3)" },

    // === SERTIFIKASI & KOMPETENSI ===
    { rule_id:"R091", category:"Sertifikasi", priority:1, conditions:[], result:{sertifikasi_info:true}, template:"Sertifikat kompetensi dari lembaga terakreditasi dapat diakui sebagai **pengganti mata kuliah** tertentu melalui proses asesmen RPL (Rekognisi Pembelajaran Lampau) di program studi.", source:"Panduan MBKM UNILA 2022 Pasal 8" },

    // === PROGRAM INTERNASIONAL ===
    { rule_id:"R092", category:"Internasional", priority:1, conditions:[{field:"ipk",op:">=",val:3.0},{field:"semester",op:">=",val:3}], result:{boleh_exchange:true}, template:"Mahasiswa dengan IPK ≥3.00 dan minimal semester 3 dapat mendaftar program **Student Exchange internasional** yang bermitra dengan UNILA.", source:"Panduan MBKM UNILA 2022 Pasal 9" },

    // === KONSELING & KESEHATAN ===
    { rule_id:"R093", category:"Kesehatan", priority:1, conditions:[], result:{konseling:true}, template:"UNILA menyediakan layanan **Konseling Akademik dan Psikologi** melalui Unit Layanan Konseling Kemahasiswaan (ULK). Mahasiswa dapat konsultasi gratis.", source:"Panduan Kemahasiswaan UNILA" },

    // === ORGANISASI MAHASISWA ===
    { rule_id:"R094", category:"Kemahasiswaan", priority:1, conditions:[], result:{ormawa:true}, template:"Kegiatan di ORMAWA (Organisasi Mahasiswa) dapat dikonversi menjadi nilai akademik melalui mekanisme **Surat Keterangan Pendamping Ijazah (SKPI)** dan kredit kegiatan kemahasiswaan.", source:"Panduan Kemahasiswaan UNILA Pasal 15" },

    // === KURIKULUM ===
    { rule_id:"R095", category:"Kurikulum", priority:1, conditions:[], result:{kurikulum_info:true}, template:"Kurikulum UNILA mengacu pada **KKNI (Kerangka Kualifikasi Nasional Indonesia)** level 6 untuk S1, yang mencakup kompetensi utama, pendukung, dan lainnya.", source:"Peraturan Akademik UNILA 2025 Bab IV Pasal 10" },
    { rule_id:"R096", category:"Kurikulum", priority:1, conditions:[], result:{matakuliah_wajib:true}, template:"Mata kuliah wajib universitas UNILA meliputi: Agama, Pancasila, Kewarganegaraan, Bahasa Indonesia, dan Bahasa Inggris. Total ±10 SKS dan wajib lulus minimal C.", source:"Peraturan Akademik UNILA 2025 Bab IV Pasal 10" },

    // === PERPUSTAKAAN ===
    { rule_id:"R097", category:"Perpustakaan", priority:1, conditions:[], result:{perpus:true}, template:"Akses perpustakaan UNILA menggunakan KTM aktif. Mahasiswa dapat meminjam maksimal **3 buku selama 1 minggu**. Denda keterlambatan Rp 500/hari/buku.", source:"Peraturan Perpustakaan UNILA" },

    // === TUGAS AKHIR ALTERNATIF ===
    { rule_id:"R098", category:"TugasAkhir", priority:1, conditions:[], result:{ta_alternatif:true}, template:"Beberapa program studi di UNILA mengizinkan **Tugas Akhir alternatif** selain skripsi: laporan magang (PKL), artikel jurnal ilmiah, atau proyek akhir terapan.", source:"Peraturan Akademik UNILA 2025 Bab IX Pasal 43" },

    // === SISTEM INFORMASI AKADEMIK ===
    { rule_id:"R099", category:"SIAKAD", priority:1, conditions:[], result:{siakad:true}, template:"SIAKAD UNILA (siakad.unila.ac.id) adalah portal resmi untuk: pengisian KRS, melihat jadwal kuliah, melihat nilai, cetak transkrip sementara, dan informasi akademik lainnya.", source:"Panduan SIAKAD UNILA" },

    // === MAHASISWA BERKEBUTUHAN KHUSUS ===
    { rule_id:"R100", category:"Inklusif", priority:1, conditions:[], result:{difabel:true}, template:"UNILA memberikan **akomodasi khusus** bagi mahasiswa berkebutuhan khusus (difabel), termasuk layanan ujian terpisah, akses fasilitas, dan pendampingan akademik. Hubungi Direktorat Kemahasiswaan.", source:"Peraturan Akademik UNILA 2025 Bab XVII Pasal 100" },

    // BONUS RULES 101-110
    { rule_id:"R101", category:"Nilai", priority:1, conditions:[{field:"ipk",op:">=",val:3.51},{field:"tidak_nilai_d",op:"==",val:true},{field:"tidak_nilai_e",op:"==",val:true}], result:{cumlaude_valid:true}, template:"Untuk predikat Cum Laude yang sah, IPK harus ≥3.51 **tanpa nilai D atau E** dalam transkrip dan menyelesaikan studi dalam waktu normal (≤8 semester).", source:"Peraturan Akademik UNILA 2025 Pasal 77" },
    { rule_id:"R102", category:"Skripsi", priority:1, conditions:[], result:{max_waktu_skripsi:true}, template:"Masa pengerjaan skripsi maksimal adalah **2 semester** sejak judul disetujui. Jika melebihi batas, mahasiswa harus mengganti judul dan pembimbing.", source:"Peraturan Akademik UNILA 2025" },
    { rule_id:"R103", category:"DO", priority:1, conditions:[{field:"ipk",op:"<",val:1.0},{field:"semester",op:">=",val:2}], result:{do_sangat_beresiko:true}, template:"🚨 **KRITIS:** IPK {ipk} sangat rendah (< 1.00). Segera temui Pembimbing Akademik, Ketua Program Studi, dan Wakil Dekan Bidang Akademik untuk evaluasi darurat.", source:"Peraturan Akademik UNILA 2025 Pasal 48" },
    { rule_id:"R104", category:"DO", priority:1, conditions:[{field:"semester",op:"==",val:4},{field:"sks_lulus",op:"<",val:40}], result:{resiko_do:true}, template:"⚠️ **PERINGATAN PUTUS STUDI**: Semester IV dengan SKS lulus < 40 atau IPK < 2.00 berisiko dikenakan putus studi.", source:"Peraturan Akademik UNILA 2025 Pasal 48" },
    { rule_id:"R105", category:"DO", priority:1, conditions:[{field:"semester",op:"==",val:8},{field:"sks_lulus",op:"<",val:80}], result:{resiko_do:true}, template:"⚠️ **PERINGATAN PUTUS STUDI**: Semester VIII dengan SKS lulus < 80 atau IPK < 2.00 berisiko dikenakan putus studi.", source:"Peraturan Akademik UNILA 2025 Pasal 48" },
  
  ],

  intents: [
    { id:"maksimal_sks", patterns:["berapa sks","maksimal sks","ambil sks","jumlah sks","sks semester","sks bisa diambil","beban sks","limit sks"], facts_needed:["ipk"], category:"SKS" },
    { id:"syarat_uas", patterns:["syarat uas","ikut uas","boleh uas","ujian akhir semester","uas bisa","kehadiran uas","presensi uas","kehadiran saya uas","presensi saya uas","kehadiran uas saya","presensi uas saya"], facts_needed:["presensi","administrasi"], category:"UAS" },
    { id:"syarat_uts", patterns:["syarat uts","ikut uts","boleh uts","ujian tengah semester","uts bisa","kehadiran uts"], facts_needed:["presensi"], category:"UTS" },
    { id:"cuti", patterns:["cuti akademik","izin cuti","mengajukan cuti","prosedur cuti","syarat cuti","cuti kuliah","cuti studi"], facts_needed:["semester"], category:"Cuti" },
    { id:"semester_pendek", patterns:["semester pendek","sp kuliah","kuliah sp","daftar sp","semester pendek bisa","ambil sp"], facts_needed:["ipk","semester"], category:"SemesterPendek" },
    { id:"skripsi", patterns:["skripsi","tugas akhir","pengajuan skripsi","syarat skripsi","daftar skripsi","sidang skripsi","seminar proposal"], facts_needed:["sks_lulus","ipk"], category:"Skripsi" },
    { id:"yudisium", patterns:["yudisium","syarat yudisium","daftar yudisium","wisuda yudisium","kelulusan","lulus kuliah"], facts_needed:["sks_lulus","ipk","skripsi","kkn"], category:"Yudisium" },
    { id:"wisuda", patterns:["wisuda","daftar wisuda","kapan wisuda","upacara wisuda","jadwal wisuda"], facts_needed:["yudisium"], category:"Wisuda" },
    { id:"registrasi", patterns:["registrasi","herregistrasi","daftar ulang","krs","pengisian krs","isi krs","update krs"], facts_needed:["administrasi"], category:"Registrasi" },
    { id:"drop_out", patterns:["do","drop out","dikeluarkan","ancaman do","beresiko do","batas studi","maksimal semester"], facts_needed:["semester","ipk","sks_lulus"], category:"DO" },
    { id:"kkn", patterns:["kkn","kuliah kerja nyata","syarat kkn","daftar kkn","program kkn","mengikuti kkn","ikut kkn","persyaratan kkn"], facts_needed:["sks_lulus","ipk","semester"], category:"KKN" },
    { id:"pkl", patterns:["pkl","praktik kerja lapangan","magang","syarat pkl","daftar pkl","program magang","kp","kerja praktik","mengikuti pkl","ikut pkl","persyaratan pkl","syarat kp","mengikuti kp"], facts_needed:["sks_lulus","semester"], category:"PKL" },
    { id:"nilai", patterns:["nilai","sistem nilai","skala nilai","huruf mutu","indeks prestasi","ip semester"], facts_needed:[], category:"Nilai" },
    { id:"ipk", patterns:["ipk","indeks prestasi kumulatif","status ipk","kategori ipk","ipk saya"], facts_needed:["ipk"], category:"IPK" },
    { id:"predikat", patterns:["predikat","cumlaude","cum laude","sangat memuaskan","predikat kelulusan","gelar kehormatan"], facts_needed:["ipk"], category:"Yudisium" },
    { id:"mbkm", patterns:["mbkm","merdeka belajar","kampus merdeka","magang mbkm","studi independen","exchange"], facts_needed:["ipk","semester"], category:"MBKM" },
    { id:"kehadiran", patterns:["kehadiran","absensi","presensi","hadir kuliah","bolos","izin kuliah","kehadiran saya","presensi saya","kehadiran kuliah","presensi kuliah"], facts_needed:["presensi"], category:"Kehadiran" },
    { id:"administrasi", patterns:["administrasi","surat keterangan","ktm","legalisir","baak","dokumen"], facts_needed:[], category:"Administrasi" },
    { id:"keuangan", patterns:["ukt","biaya kuliah","pembayaran","keuangan","beasiswa","cicilan ukt"], facts_needed:[], category:"Keuangan" },
    { id:"siakad", patterns:["siakad","sistem informasi akademik","portal akademik","login siakad","website akademik"], facts_needed:[], category:"SIAKAD" },
  ]


};

export default KNOWLEDGE_BASE;
